export const menu = {
  1: "/",
  2: "/histories",
  3: "/drivers",
  4: "/treasurers",
  5: "/atm-technicans",
  6: "/cars",
  7: "/devices",
  8: "/users",
  9: "/permissions",
  10: "/rfids",
  11: "/transaction-points",
  12: "/sample-routes",
  13: "/segmentations",
  14: "/reports",
  15: "/units",
  16: "/escorts",
}

export const revertMenu = {
  "/": "1",
  "/histories": "2",
  "/drivers": "3",
  "/treasurers": "4",
  "/atm-technicans": "5",
  "/cars": "6",
  "/devices": "7",
  "/users": "8",
  "/permissions": "9",
  "/rfids": "10",
  "/transaction-points": "11",
  "/sample-routes": "12",
  "/segmentations": "13",
  "/reports": "14",
  "/units":"15",
  "/escorts": "16",
}

export const menuParentKey = {
  3: ["sub1", "sub1-1"],
  4: ["sub1", "sub1-1"],
  5: ["sub1", "sub1-1"],
  6: ["sub1", "sub1-2"],
  7: ["sub1", "sub1-2"],
  8: ["sub1", "sub1-3"],
  9: ["sub1", "sub1-3"],
  10: ["sub1"],
  11: ["sub1"],
  12: ["sub2"],
  13: ["sub2"],
  15: ["sub1-3"],
  16: ["sub1", "sub1-1"],
}
